apiVersion: apps/v1
kind: Deployment
metadata:
  name: bp-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bp-challenge
  template:
    metadata:
      labels:
        app: bp-challenge
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: bp-challenge
        image: appscr.azurecr.io/bp-challenge
        ports:
        - containerPort: 5000
        env:
        - name: API_KEY
          value: "2f5ae96c-b558-4c7b-a590-a501ae1c3f6c"
---
apiVersion: v1
kind: Service
metadata:
  name: bp-challenge
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: bp-challenge
